name: Run tests and deploy if release tag

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test

  deploy_to_staging:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/tags/v')
      && (
        contains(github.ref, 'alpha')
        || contains(github.ref, 'beta')
      )
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
        env:
          LABORATORIA_CORE_API_URL: https://us-central1-outpost-staging-344823.cloudfunctions.net/core-api
          FIREBASE_API_KEY: AIzaSyAXbaEbpq8NOfn0r8mIrcoHvoGRkJThwdc
          FIREBASE_PROJECT: laboratoria-la
          SENTRY_DSN: https://f63bf80837e74128a8f4e7701b0efe34@o342590.ingest.sentry.io/4505591507255296
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOTCAMP_E078F }}
          channelId: staging
          expires: 30d
          projectId: bootcamp-e078f

  deploy_to_production:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/tags/v')
      && !contains(github.ref, 'alpha')
      && !contains(github.ref, 'beta')
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
        env:
          FIREBASE_API_KEY: AIzaSyAXbaEbpq8NOfn0r8mIrcoHvoGRkJThwdc
          FIREBASE_PROJECT: laboratoria-la
          SENTRY_DSN: https://f63bf80837e74128a8f4e7701b0efe34@o342590.ingest.sentry.io/4505591507255296
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOTCAMP_E078F }}
          channelId: live
          projectId: bootcamp-e078f
